name: thesis
channels:
  - conda-forge
dependencies:
  - python=3.13.12
  - numpy=2.4.2
  - mujoco=3.3.6
  - opencv=4.13.0
  - pandas=3.0.0
  - pyyaml=6.0.3
  - pip
  - pip:
      - mediapipe==0.10.32
      - mediapy==1.2.6
      - oneeurofilter==0.2.1
      - .

